name: CI/CD â€“ Python & Docker

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  # jeppebs/billedegenkendelse
  IMAGE_NAME: jeppebs/billedegenkendelse

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

        #Python build
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests if present
        run: |
          if [ -d tests ] || [ -f pytest.ini ]; then
            pip install pytest
            pytest
          else
            echo "No tests found, skipping."
          fi

        # Docker build & push 
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate Version Number
        id: vars
        run: |
          # Get the current run number (e.g., 1, 2, 3...)
          run_num=${{ github.run_number }}
      
          # Calculate Major and Minor version numbers
          # Logic: Increment Major number every 10 runs. Minor resets to 1 after 10.
          # (run_num - 1) ensures we start at 1.1 simple math :)
          major=$(( (run_num - 1) / 10 + 1 ))
          minor=$(( (run_num - 1) % 10 + 1 ))
      
          version="${major}.${minor}"

          # First echo is just for logging :)
          echo "Generated Version: $version"
          echo "version=$version" >> $GITHUB_OUTPUT


      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./Python-code
          file: ./Python-code/Billedegenkendelse/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          build-args: |
            APP_VERSION=${{ steps.vars.outputs.version }}
